export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const VERIFY_MOBILE_REQUEST = 'VERIFY_MOBILE_REQUEST';
export const VERIFY_MOBILE_SUCCESS = 'VERIFY_MOBILE_SUCCESS';
export const VERIFY_MOBILE_FAIL = 'VERIFY_MOBILE_FAIL';


export const RESEND_MOBILE_REQUEST = 'RESEND_MOBILE_REQUEST';
export const RESEND_MOBILE_SUCCESS = 'RESEND_MOBILE_SUCCESS';
export const RESEND_MOBILE_FAIL = 'RESEND_MOBILE_FAIL';